import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";

import "./globals.css";
import { auth } from "@/auth";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const session = await auth();

	return (
		<SessionProvider session={session}>
			<html lang="en">
				<body className="antialiased">{children}</body>
			</html>
		</SessionProvider>
	);
}
